import 'styles/tailwind.css';

import { FontProvider } from 'components/context/font';
import { ThemeProvider } from 'components/context/theme';
import { SmoothScrollProvider } from 'components/context/scroll';
/* import { CursorProvider } from 'components/context/cursor'; */

import { Navigation } from 'components/sections/navigation';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <FontProvider>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          {/* <CursorProvider> */}
            <Navigation />
            <SmoothScrollProvider>{children}</SmoothScrollProvider>
          {/* </CursorProvider> */}
        </ThemeProvider>
      </FontProvider>
    </html>
  );
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
